### ISSUE TITLE
Libfolia generated document with invalid ids (not an NCName)

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/libfolia#5] opened 2016-07-21 12:08 UTC
Martin came accross the following document:

```
<FoLiA generator="libfolia-v0.11" xml:id="_gid001199401_01_0096" xmlns="http://ilk.uvt.nl/folia" xmlns:xlink="http://www.w3.org/1999/xlink">
```

Which fails to be read because: 

```
reason: XML error: XML error: '_gid001199401_01_0096' is not a valid NCName. (must start with character). 
```

I think we need some kind of quick check on ID setting, may possibly be an issue for the python version too.

**Comment by kosloot** [comment] 2016-10-17 12:07
libfolia check on NCnames, normaly.
@martinreynaert cab you provide the chain of events that triggered thus file?
also: input file and tools used?

**Comment by kosloot** [comment] 2016-10-17 12:25
We are unable to reproduce this with our tools.
I doubt if the file was indeed generated with libfolia-v0.11. . But otoh: that is a really old version, so maybe a safeguard was in those days.
@martinreynaert please provide more info

**Comment by kosloot** [comment] 2016-11-01 15:09
One addition: libfolia rejected id's starting with an underscore '_'. I think this is an error.
id's may start with an underscore.
libfolia will be adapted tot accept this in the future.

**Comment by kosloot** [comment] 2016-11-08 14:08
As far is I know this is fixed now.

**Closed by kosloot** 2016-11-08 14:08 UTC
Labels: bug, waiting
